package provision

import (
	"context"
	"fmt"
	"strings"

	"github.com/ocfp/ocfp-cli-go/internal/config"
	"github.com/ocfp/ocfp-cli-go/internal/logger"
)

// EnvironmentManager handles shell and system environment configuration.
type EnvironmentManager struct {
	config   *config.Config
	provider string
	log      logger.Logger
}

// NewEnvironmentManager creates a new environment manager.
func NewEnvironmentManager(provider string, cfg *config.Config) *EnvironmentManager {
	return &EnvironmentManager{
		config:   cfg,
		provider: provider,
		log:      logger.Get(),
	}
}

// GetSystemEnvironmentVarsForPreview exposes the key/value set for previews.
func (em *EnvironmentManager) GetSystemEnvironmentVarsForPreview() map[string]string {
	return em.getSystemEnvironmentVars()
}

// GenerateShellEnvironmentScript generates .bashrc configuration.
func (em *EnvironmentManager) GenerateShellEnvironmentScript(_ctx context.Context) string {
	// Preallocate a sensible capacity; mostly fixed-size content
	lines := make([]string, 0, scriptBufferEnvironmentBase)

	lines = append(lines, "# Shell environment configuration")
	lines = append(lines, "")

	// Generate bashrc additions
	bashrcContent := em.generateBashrcAdditions()

	lines = append(lines, "# Check if shell environment already configured")
	lines = append(lines, `if grep -q "OCFP Environment Configuration" "$HOME/.bashrc" 2>/dev/null; then`)
	lines = append(lines, "    log_success 'Shell environment already configured'")
	lines = append(lines, "else")
	lines = append(lines, "    log_info 'Configuring shell environment'")
	lines = append(lines, "    cat >> \"$HOME/.bashrc\" << 'BASHRC_EOF'")
	lines = append(lines, bashrcContent)
	lines = append(lines, "BASHRC_EOF")
	lines = append(lines, "    log_success 'Shell environment configured'")
	lines = append(lines, "fi")
	lines = append(lines, "")

	return strings.Join(lines, "\n")
}

// GenerateSystemEnvironmentScript generates /etc/environment and /etc/profile.d setup.
func (em *EnvironmentManager) GenerateSystemEnvironmentScript(_ctx context.Context) string {
	envVars := em.getSystemEnvironmentVars()
	lines := make([]string, 0, scriptBufferEnvironment+scriptBufferEnvironmentPerItem*len(envVars))

	lines = append(lines, "# System environment configuration")
	lines = append(lines, "")

	lines = append(lines, em.generateEnvironmentGuardClause()...)
	lines = append(lines, em.generateEtcEnvironmentUpdate(envVars)...)
	lines = append(lines, em.generateProfileDScript(envVars)...)

	return strings.Join(lines, "\n")
}

// generateBashrcAdditions creates the bashrc configuration content.
func (em *EnvironmentManager) generateBashrcAdditions() string {
	var content strings.Builder

	em.addBasicEnvironmentConfig(&content)
	em.addEditorConfig(&content)
	em.addAliases(&content)
	em.addOCFPConfig(&content)
	em.addProviderConfig(&content)
	em.addToolConfigurations(&content)

	return content.String()
}

func (em *EnvironmentManager) generateEnvironmentGuardClause() []string {
	return []string{
		"if [ -n \"${OCFP_BLOC:-}\" ]; then",
		"",
	}
}

func (em *EnvironmentManager) generateEtcEnvironmentUpdate(envVars map[string]string) []string {
	lines := make([]string, 0, 8+len(envVars)+len(envVars)+1+1+len(envVars)+1)
	lines = append(lines,
		"    # Update /etc/environment atomically (merge desired keys)",
		"    TMP_ENV=$(mktemp /tmp/ocfp-environment.XXXXXX)",
		"    if [ -f /etc/environment ]; then",
		"        sudo cp /etc/environment \"$TMP_ENV\"",
		"        sudo chown $(whoami) \"$TMP_ENV\"",
		"    else",
		"        : > \"$TMP_ENV\"",
		"    fi",
	)

	for key := range envVars {
		lines = append(lines, fmt.Sprintf("    sed -i -E '/^%s=/d' \"$TMP_ENV\"", key))
	}

	for key, value := range envVars {
		desired := fmt.Sprintf("%s=%s", key, value)
		lines = append(lines, fmt.Sprintf("    echo '%s' >> \"$TMP_ENV\"", desired))
	}

	lines = append(lines, "    sudo install -m 0644 \"$TMP_ENV\" /etc/environment")
	lines = append(lines, "    rm -f \"$TMP_ENV\"")

	for key, value := range envVars {
		desired := fmt.Sprintf("%s=%s", key, value)
		lines = append(lines, fmt.Sprintf("    grep -qF '%s' /etc/environment && log_success '%s set in /etc/environment' || log_warning '%s missing in /etc/environment'", desired, key, key))
	}

	lines = append(lines, "    ")

	return lines
}

func (em *EnvironmentManager) generateProfileDScript(envVars map[string]string) []string {
	lines := make([]string, 0, 7+len(envVars)+12) //nolint:mnd
	lines = append(lines,
		"    # Create /etc/profile.d/ocfp.sh (atomic write)",
		"    log_info 'Creating /etc/profile.d/ocfp.sh'",
		"    sudo tee /tmp/ocfp_profile.sh >/dev/null << 'PROFILE_EOF'",
		"#!/bin/sh",
		"# OCFP environment variables",
		"# Generated by ocfp bastion provisioning",
		"",
	)

	// Source Linuxbrew so brew-installed binaries are on PATH for login shells
	lines = append(lines,
		"# Linuxbrew environment",
		`if [ -x /home/linuxbrew/.linuxbrew/bin/brew ]; then`,
		`    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"`,
		"fi",
		"",
	)

	for key, value := range envVars {
		lines = append(lines, fmt.Sprintf("export %s='%s'", key, value))
	}

	lines = append(lines, "PROFILE_EOF")
	lines = append(lines, "    sudo install -m 0644 /tmp/ocfp_profile.sh /etc/profile.d/ocfp.sh")
	lines = append(lines, "    # Verify write")
	lines = append(lines, "    if [ -f /etc/profile.d/ocfp.sh ] && grep -q 'OCFP environment variables' /etc/profile.d/ocfp.sh; then")
	lines = append(lines, "        log_success '/etc/profile.d/ocfp.sh created'")
	lines = append(lines, "    else")
	lines = append(lines, "        log_error 'Failed to create /etc/profile.d/ocfp.sh'")
	lines = append(lines, "    fi")
	lines = append(lines, "else")
	lines = append(lines, "    log_info 'No OCFP_BLOC provided, skipping system environment setup'")
	lines = append(lines, "fi")
	lines = append(lines, "")

	return lines
}

func (em *EnvironmentManager) addBasicEnvironmentConfig(content *strings.Builder) {
	content.WriteString("\n# OCFP Environment Configuration\n")
	content.WriteString("export OCFP_ROOT=\"$HOME/ocfp\"\n")
	content.WriteString("export OCFP_CLI=\"$HOME/ocfp/cli\"\n")
	content.WriteString("export DEPLOYMENTS_DIR=\"$HOME/ocfp/deployments\"\n")
	content.WriteString("export RELEASES_DIR=\"$HOME/ocfp/releases\"\n")
	content.WriteString("export ARTIFACTS_DIR=\"$HOME/ocfp/artifacts\"\n")
	content.WriteString("export PATH=\"$HOME/bin:$PATH\"\n")
	content.WriteString("# Linuxbrew environment\n")
	content.WriteString("eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\"\n")
	content.WriteString("\n")
}

func (em *EnvironmentManager) addEditorConfig(content *strings.Builder) {
	content.WriteString("# Editor configuration\n")
	content.WriteString("export EDITOR=nvim\n")
	content.WriteString("export VISUAL=nvim\n")
	content.WriteString("\n")
}

func (em *EnvironmentManager) addAliases(content *strings.Builder) {
	// Useful aliases
	content.WriteString("# Useful aliases\n")
	content.WriteString("alias ll='ls -la'\n")
	content.WriteString("alias la='ls -A'\n")
	content.WriteString("alias l='ls -CF'\n")
	content.WriteString("alias vi=nvim\n")
	content.WriteString("alias vim=nvim\n")
	content.WriteString("\n")

	// BOSH aliases
	content.WriteString("# BOSH aliases\n")
	content.WriteString("alias b='bosh'\n")
	content.WriteString("alias be='bosh env'\n")
	content.WriteString("alias bd='bosh deployments'\n")
	content.WriteString("\n")

	// Navigation aliases
	content.WriteString("# Navigation aliases\n")
	content.WriteString("alias cdops='cd $DEPLOYMENTS_DIR'\n")
	content.WriteString("alias cdreleases='cd $RELEASES_DIR'\n")
	content.WriteString("alias cdartifacts='cd $ARTIFACTS_DIR'\n")
	content.WriteString("\n")

	// tmux configuration
	content.WriteString("# tmux configuration\n")
	content.WriteString("alias t='tmux'\n")
	content.WriteString("alias ta='tmux attach'\n")
	content.WriteString("alias tn='tmux new-session'\n")
	content.WriteString("\n")
}

func (em *EnvironmentManager) addOCFPConfig(content *strings.Builder) {
	content.WriteString("# OCFP bloc configuration\n")
	content.WriteString("if [ -n \"$OCFP_BLOC\" ]; then\n")
	content.WriteString("    export OCFP_BLOC=\"$OCFP_BLOC\"\n")
	content.WriteString("fi\n")
	content.WriteString("\n")
}

func (em *EnvironmentManager) addProviderConfig(content *strings.Builder) {
	content.WriteString("# Provider configuration\n")
	content.WriteString("if [ -n \"$OCFP_PROVIDER\" ]; then\n")
	content.WriteString("    export OCFP_PROVIDER=\"$OCFP_PROVIDER\"\n")
	content.WriteString("    \n")
	content.WriteString("    case \"$OCFP_PROVIDER\" in\n")
	em.addStackitProviderConfig(content)
	em.addAWSProviderConfig(content)
	em.addAzureProviderConfig(content)
	em.addGCPProviderConfig(content)
	content.WriteString("    esac\n")
	content.WriteString("fi\n")
	content.WriteString("\n")
}

func (em *EnvironmentManager) addStackitProviderConfig(content *strings.Builder) {
	content.WriteString("        stackit)\n")
	content.WriteString("            # STACKIT-specific configuration\n")
	content.WriteString("            [ -n \"$STACKIT_PROJECT_ID\" ] && export STACKIT_PROJECT_ID=\"$STACKIT_PROJECT_ID\"\n")
	content.WriteString("            [ -n \"$STACKIT_ORG_ID\" ] && export STACKIT_ORG_ID=\"$STACKIT_ORG_ID\"\n")
	content.WriteString("            [ -n \"$STACKIT_REGION\" ] && export STACKIT_REGION=\"$STACKIT_REGION\"\n")
	content.WriteString("            alias st='stackit'\n")
	content.WriteString("            ;;\n")
}

func (em *EnvironmentManager) addAWSProviderConfig(content *strings.Builder) {
	content.WriteString("        aws)\n")
	content.WriteString("            # AWS-specific configuration\n")
	content.WriteString("            [ -n \"$AWS_ACCESS_KEY_ID\" ] && export AWS_ACCESS_KEY_ID=\"$AWS_ACCESS_KEY_ID\"\n")
	content.WriteString("            [ -n \"$AWS_SECRET_ACCESS_KEY\" ] && export AWS_SECRET_ACCESS_KEY=\"$AWS_SECRET_ACCESS_KEY\"\n")
	content.WriteString("            [ -n \"$AWS_DEFAULT_REGION\" ] && export AWS_DEFAULT_REGION=\"$AWS_DEFAULT_REGION\"\n")
	content.WriteString("            ;;\n")
}

func (em *EnvironmentManager) addAzureProviderConfig(content *strings.Builder) {
	content.WriteString("        azure)\n")
	content.WriteString("            # Azure-specific configuration\n")
	content.WriteString("            alias az='azure'\n")
	content.WriteString("            ;;\n")
}

func (em *EnvironmentManager) addGCPProviderConfig(content *strings.Builder) {
	content.WriteString("        gcp)\n")
	content.WriteString("            # GCP-specific configuration\n")
	content.WriteString("            [ -n \"$GCP_PROJECT_ID\" ] && export GCP_PROJECT_ID=\"$GCP_PROJECT_ID\"\n")
	content.WriteString("            ;;\n")
}

func (em *EnvironmentManager) addToolConfigurations(content *strings.Builder) {
	// NVM configuration
	content.WriteString("# NVM configuration\n")
	content.WriteString("if [ -f \"$HOME/.nvm/nvm.sh\" ]; then\n")
	content.WriteString("    source \"$HOME/.nvm/nvm.sh\"\n")
	content.WriteString("    [ -s \"$HOME/.nvm/bash_completion\" ] && source \"$HOME/.nvm/bash_completion\"\n")
	content.WriteString("fi\n")
	content.WriteString("\n")

	// Bun configuration
	content.WriteString("# Bun configuration\n")
	content.WriteString("if [ -d \"$HOME/.bun\" ]; then\n")
	content.WriteString("    export BUN_INSTALL=\"$HOME/.bun\"\n")
	content.WriteString("    export PATH=\"$BUN_INSTALL/bin:$PATH\"\n")
	content.WriteString("fi\n")
	content.WriteString("\n")

	// Go version pinning (keg-only formula needs explicit PATH)
	content.WriteString("# Go (brew keg-only versioned formula)\n")
	content.WriteString("if [ -d \"$(brew --prefix)/opt/go@1.24/bin\" ] 2>/dev/null; then\n")
	content.WriteString("    export PATH=\"$(brew --prefix)/opt/go@1.24/bin:$PATH\"\n")
	content.WriteString("fi\n")
	content.WriteString("\n")
}

// getSystemEnvironmentVars returns environment variables for system configuration.
func (em *EnvironmentManager) getSystemEnvironmentVars() map[string]string {
	vars := map[string]string{
		"OCFP_BLOC":           em.config.Name,
		"OCFP_PROVIDER":       em.provider,
		"GENESIS_ENVIRONMENT": em.config.Name,
	}

	// Add provider-specific variables from config
	switch em.provider {
	case providerStackit:
		if em.config.ProjectID != "" {
			vars["STACKIT_PROJECT_ID"] = em.config.ProjectID
		}

		if em.config.OrgID != "" {
			vars["STACKIT_ORG_ID"] = em.config.OrgID
		}

		if em.config.Region != "" {
			vars["STACKIT_REGION"] = em.config.Region
		}
	case providerAWS:
		if em.config.AccessKeyID != "" {
			vars["AWS_ACCESS_KEY_ID"] = em.config.AccessKeyID
		}

		if em.config.SecretAccessKey != "" {
			vars["AWS_SECRET_ACCESS_KEY"] = em.config.SecretAccessKey
		}

		if em.config.Region != "" {
			vars["AWS_DEFAULT_REGION"] = em.config.Region
		}
	case providerAzure:
		if em.config.SubscriptionID != "" {
			vars["AZURE_SUBSCRIPTION_ID"] = em.config.SubscriptionID
		}

		if em.config.TenantID != "" {
			vars["AZURE_TENANT_ID"] = em.config.TenantID
		}

		if em.config.ClientID != "" {
			vars["AZURE_CLIENT_ID"] = em.config.ClientID
		}
	case providerGCP:
		if em.config.ProjectID != "" {
			vars["GCP_PROJECT_ID"] = em.config.ProjectID
		}
	}

	return vars
}
