package provision

import (
	"context"
	"fmt"
	"strings"

	"github.com/ocfp/ocfp-cli-go/internal/config"
	"github.com/ocfp/ocfp-cli-go/internal/logger"
)

// EnvironmentManager handles shell and system environment configuration.
type EnvironmentManager struct {
	config   *config.Config
	provider string
	log      logger.Logger
}

// NewEnvironmentManager creates a new environment manager.
func NewEnvironmentManager(provider string, cfg *config.Config) *EnvironmentManager {
	return &EnvironmentManager{
		config:   cfg,
		provider: provider,
		log:      logger.Get(),
	}
}

// GetSystemEnvironmentVarsForPreview exposes the key/value set for previews.
func (em *EnvironmentManager) GetSystemEnvironmentVarsForPreview() map[string]string {
	return em.getSystemEnvironmentVars()
}

// GenerateShellEnvironmentScript generates .bashrc configuration.
func (em *EnvironmentManager) GenerateShellEnvironmentScript(ctx context.Context) string {
	var lines []string

	lines = append(lines, "# Shell environment configuration")
	lines = append(lines, "")

	// Generate bashrc additions
	bashrcContent := em.generateBashrcAdditions()

	lines = append(lines, "# Check if shell environment already configured")
	lines = append(lines, `if grep -q "OCFP Environment Configuration" "$HOME/.bashrc" 2>/dev/null; then`)
	lines = append(lines, "    log_success 'Shell environment already configured'")
	lines = append(lines, "else")
	lines = append(lines, "    log_info 'Configuring shell environment'")
	lines = append(lines, "    cat >> \"$HOME/.bashrc\" << 'BASHRC_EOF'")
	lines = append(lines, bashrcContent)
	lines = append(lines, "BASHRC_EOF")
	lines = append(lines, "    log_success 'Shell environment configured'")
	lines = append(lines, "fi")
	lines = append(lines, "")

	return strings.Join(lines, "\n")
}

// GenerateSystemEnvironmentScript generates /etc/environment and /etc/profile.d setup.
func (em *EnvironmentManager) GenerateSystemEnvironmentScript(ctx context.Context) string {
	var lines []string

	lines = append(lines, "# System environment configuration")
	lines = append(lines, "")

	// Only proceed if we have OCFP_BLOC_NAME
	lines = append(lines, "if [ -z \"$OCFP_BLOC_NAME\" ]; then")
	lines = append(lines, "    log_info 'No OCFP_BLOC_NAME provided, skipping system environment setup'")
	lines = append(lines, "    return 0")
	lines = append(lines, "fi")
	lines = append(lines, "")

	// Prepare environment variables
	envVars := em.getSystemEnvironmentVars()

	// Build a merged /etc/environment atomically
	lines = append(lines, "# Update /etc/environment atomically (merge desired keys)")
	lines = append(lines, "TMP_ENV=$(mktemp /tmp/ocfp-environment.XXXXXX)")
	lines = append(lines, "if [ -f /etc/environment ]; then")
	lines = append(lines, "    cp /etc/environment \"$TMP_ENV\"")
	lines = append(lines, "else")
	lines = append(lines, "    : > \"$TMP_ENV\"")
	lines = append(lines, "fi")
	// Remove any existing entries for our keys
	for key := range envVars {
		lines = append(lines, fmt.Sprintf("sudo sed -i -E '/^%s=/d' \"$TMP_ENV\"", key))
	}
	// Append desired entries
	for key, value := range envVars {
		desired := fmt.Sprintf("%s=%s", key, value)
		lines = append(lines, fmt.Sprintf("echo '%s' | sudo tee -a \"$TMP_ENV\" >/dev/null", desired))
	}
	// Install atomically
	lines = append(lines, "sudo install -m 0644 \"$TMP_ENV\" /etc/environment")
	lines = append(lines, "rm -f \"$TMP_ENV\"")
	// Verify keys present
	for key, value := range envVars {
		desired := fmt.Sprintf("%s=%s", key, value)
		lines = append(lines, fmt.Sprintf("grep -qF '%s' /etc/environment && log_success '%s set in /etc/environment' || log_warning '%s missing in /etc/environment'", desired, key, key))
	}

	lines = append(lines, "")

	// Create /etc/profile.d/ocfp.sh atomically
	lines = append(lines, "# Create /etc/profile.d/ocfp.sh (atomic write)")
	lines = append(lines, "log_info 'Creating /etc/profile.d/ocfp.sh'")
	lines = append(lines, "sudo tee /tmp/ocfp_profile.sh >/dev/null << 'PROFILE_EOF'")
	lines = append(lines, "#!/bin/sh")
	lines = append(lines, "# OCFP environment variables")
	lines = append(lines, "# Generated by ocfp bastion provisioning")
	lines = append(lines, "")

	for key, value := range envVars {
		lines = append(lines, fmt.Sprintf("export %s='%s'", key, value))
	}

	lines = append(lines, "PROFILE_EOF")
	lines = append(lines, "sudo install -m 0644 /tmp/ocfp_profile.sh /etc/profile.d/ocfp.sh")
	lines = append(lines, "# Verify write")
	lines = append(lines, "if [ -f /etc/profile.d/ocfp.sh ] && grep -q 'OCFP environment variables' /etc/profile.d/ocfp.sh; then")
	lines = append(lines, "    log_success '/etc/profile.d/ocfp.sh created'")
	lines = append(lines, "else")
	lines = append(lines, "    log_error 'Failed to create /etc/profile.d/ocfp.sh'")
	lines = append(lines, "fi")
	lines = append(lines, "")

	return strings.Join(lines, "\n")
}

// generateBashrcAdditions creates the bashrc configuration content.
func (em *EnvironmentManager) generateBashrcAdditions() string {
	var content strings.Builder

	content.WriteString("\n# OCFP Environment Configuration\n")
	content.WriteString("export OCFP_ROOT=\"$HOME/ocfp\"\n")
	content.WriteString("export OCFP_CLI=\"$HOME/ocfp/cli\"\n")
	content.WriteString("export DEPLOYMENTS_DIR=\"$HOME/ocfp/deployments\"\n")
	content.WriteString("export RELEASES_DIR=\"$HOME/ocfp/releases\"\n")
	content.WriteString("export ARTIFACTS_DIR=\"$HOME/ocfp/artifacts\"\n")
	content.WriteString("export PATH=\"$HOME/bin:$PATH\"\n")
	content.WriteString("# Go is installed via snap, no need to modify PATH\n")
	content.WriteString("\n")

	// Editor configuration
	content.WriteString("# Editor configuration\n")
	content.WriteString("export EDITOR=nvim\n")
	content.WriteString("export VISUAL=nvim\n")
	content.WriteString("\n")

	// Useful aliases
	content.WriteString("# Useful aliases\n")
	content.WriteString("alias ll='ls -la'\n")
	content.WriteString("alias la='ls -A'\n")
	content.WriteString("alias l='ls -CF'\n")
	content.WriteString("alias vi=nvim\n")
	content.WriteString("alias vim=nvim\n")
	content.WriteString("\n")

	// BOSH aliases
	content.WriteString("# BOSH aliases\n")
	content.WriteString("alias b='bosh'\n")
	content.WriteString("alias be='bosh env'\n")
	content.WriteString("alias bd='bosh deployments'\n")
	content.WriteString("\n")

	// Navigation aliases
	content.WriteString("# Navigation aliases\n")
	content.WriteString("alias cdops='cd $DEPLOYMENTS_DIR'\n")
	content.WriteString("alias cdreleases='cd $RELEASES_DIR'\n")
	content.WriteString("alias cdartifacts='cd $ARTIFACTS_DIR'\n")
	content.WriteString("\n")

	// tmux configuration
	content.WriteString("# tmux configuration\n")
	content.WriteString("alias t='tmux'\n")
	content.WriteString("alias ta='tmux attach'\n")
	content.WriteString("alias tn='tmux new-session'\n")
	content.WriteString("\n")

	// Add bloc name if available via environment variable
	content.WriteString("# OCFP bloc configuration\n")
	content.WriteString("if [ -n \"$OCFP_BLOC_NAME\" ]; then\n")
	content.WriteString("    export OCFP_BLOC_NAME=\"$OCFP_BLOC_NAME\"\n")
	content.WriteString("fi\n")
	content.WriteString("\n")

	// Add provider-specific environment variables and aliases
	content.WriteString("# Provider configuration\n")
	content.WriteString("if [ -n \"$OCFP_PROVIDER\" ]; then\n")
	content.WriteString("    export OCFP_PROVIDER=\"$OCFP_PROVIDER\"\n")
	content.WriteString("    \n")
	content.WriteString("    case \"$OCFP_PROVIDER\" in\n")
	content.WriteString("        stackit)\n")
	content.WriteString("            # STACKIT-specific configuration\n")
	content.WriteString("            [ -n \"$STACKIT_PROJECT_ID\" ] && export STACKIT_PROJECT_ID=\"$STACKIT_PROJECT_ID\"\n")
	content.WriteString("            [ -n \"$STACKIT_ORG_ID\" ] && export STACKIT_ORG_ID=\"$STACKIT_ORG_ID\"\n")
	content.WriteString("            [ -n \"$STACKIT_REGION\" ] && export STACKIT_REGION=\"$STACKIT_REGION\"\n")
	content.WriteString("            alias st='stackit'\n")
	content.WriteString("            ;;\n")
	content.WriteString("        aws)\n")
	content.WriteString("            # AWS-specific configuration\n")
	content.WriteString("            [ -n \"$AWS_ACCESS_KEY_ID\" ] && export AWS_ACCESS_KEY_ID=\"$AWS_ACCESS_KEY_ID\"\n")
	content.WriteString("            [ -n \"$AWS_SECRET_ACCESS_KEY\" ] && export AWS_SECRET_ACCESS_KEY=\"$AWS_SECRET_ACCESS_KEY\"\n")
	content.WriteString("            [ -n \"$AWS_DEFAULT_REGION\" ] && export AWS_DEFAULT_REGION=\"$AWS_DEFAULT_REGION\"\n")
	content.WriteString("            ;;\n")
	content.WriteString("        azure)\n")
	content.WriteString("            # Azure-specific configuration\n")
	content.WriteString("            alias az='azure'\n")
	content.WriteString("            ;;\n")
	content.WriteString("        gcp)\n")
	content.WriteString("            # GCP-specific configuration\n")
	content.WriteString("            [ -n \"$GCP_PROJECT_ID\" ] && export GCP_PROJECT_ID=\"$GCP_PROJECT_ID\"\n")
	content.WriteString("            ;;\n")
	content.WriteString("    esac\n")
	content.WriteString("fi\n")
	content.WriteString("\n")

	// NVM configuration
	content.WriteString("# NVM configuration\n")
	content.WriteString("if [ -f \"$HOME/.nvm/nvm.sh\" ]; then\n")
	content.WriteString("    source \"$HOME/.nvm/nvm.sh\"\n")
	content.WriteString("    [ -s \"$HOME/.nvm/bash_completion\" ] && source \"$HOME/.nvm/bash_completion\"\n")
	content.WriteString("fi\n")
	content.WriteString("\n")

	// Bun configuration
	content.WriteString("# Bun configuration\n")
	content.WriteString("if [ -d \"$HOME/.bun\" ]; then\n")
	content.WriteString("    export BUN_INSTALL=\"$HOME/.bun\"\n")
	content.WriteString("    export PATH=\"$BUN_INSTALL/bin:$PATH\"\n")
	content.WriteString("fi\n")
	content.WriteString("\n")

	// Snap binary PATH
	content.WriteString("# Snap binaries\n")
	content.WriteString("export PATH=\"/snap/bin:$PATH\"\n")
	content.WriteString("\n")

	return content.String()
}

// getSystemEnvironmentVars returns environment variables for system configuration.
func (em *EnvironmentManager) getSystemEnvironmentVars() map[string]string {
	vars := map[string]string{
		"OCFP_BLOC_NAME": "${OCFP_BLOC_NAME}",
		"OCFP_PROVIDER":  "${OCFP_PROVIDER}",
	}

	// Add provider-specific variables
	switch em.provider {
	case "stackit":
		vars["STACKIT_PROJECT_ID"] = "${STACKIT_PROJECT_ID}"
		vars["STACKIT_ORG_ID"] = "${STACKIT_ORG_ID}"
		vars["STACKIT_REGION"] = "${STACKIT_REGION}"
	case "aws":
		vars["AWS_ACCESS_KEY_ID"] = "${AWS_ACCESS_KEY_ID}"
		vars["AWS_SECRET_ACCESS_KEY"] = "${AWS_SECRET_ACCESS_KEY}"
		vars["AWS_DEFAULT_REGION"] = "${AWS_DEFAULT_REGION}"
	case "azure":
		vars["AZURE_SUBSCRIPTION_ID"] = "${AZURE_SUBSCRIPTION_ID}"
		vars["AZURE_TENANT_ID"] = "${AZURE_TENANT_ID}"
		vars["AZURE_CLIENT_ID"] = "${AZURE_CLIENT_ID}"
	case "gcp":
		vars["GCP_PROJECT_ID"] = "${GCP_PROJECT_ID}"
	}

	return vars
}
