package precompile

import (
	"bufio"
	"fmt"
	"strings"
)

// stemcellMarkerPrefix prefixes the YAML comment that records which stemcell a
// generated pin ops file was built for. The deploy side reads it to refuse a
// cache built for the wrong stemcell. Mirrors STEMCELL_MARKER in _compiled.py.
const stemcellMarkerPrefix = "# stemcell: "

// RenderOpsFile renders a BOSH go-patch ops file that pins each release to its
// compiled tarball. Each op uses path /releases/name=X? (insert-or-replace) so
// the file is order-independent and wins when layered last over any earlier
// release stanza. The header carries the stemcell marker for the deploy-side guard.
//
// generatedBy is recorded in the header comment (e.g. "ocfp precompile cf") so
// the artifact is traceable to the command that produced it.
func RenderOpsFile(rels []Resolution, sc Stemcell, generatedBy string) ([]byte, error) {
	if len(rels) == 0 {
		return nil, fmt.Errorf("no resolutions to render")
	}

	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "# GENERATED by `%s` — do not edit by hand.\n", generatedBy)
	fmt.Fprintf(&b, "%s%s\n", stemcellMarkerPrefix, sc.String())

	for _, r := range rels {
		if r.URL == "" || r.SHA == "" {
			return nil, fmt.Errorf("release %s/%s: missing url or sha", r.Name, r.Version)
		}
		fmt.Fprintf(&b, "- type: replace\n")
		fmt.Fprintf(&b, "  path: /releases/name=%s?\n", r.Name)
		fmt.Fprintf(&b, "  value:\n")
		fmt.Fprintf(&b, "    name: %s\n", r.Name)
		fmt.Fprintf(&b, "    version: %q\n", r.Version)
		fmt.Fprintf(&b, "    url: %q\n", r.URL)
		fmt.Fprintf(&b, "    sha1: %q\n", r.SHA)
		fmt.Fprintf(&b, "    stemcell:\n")
		fmt.Fprintf(&b, "      os: %s\n", sc.OS)
		fmt.Fprintf(&b, "      version: %q\n", sc.Version)
	}

	return []byte(b.String()), nil
}

// StemcellFromOps extracts the stemcell recorded in a generated pin ops file's
// marker comment. Returns ok=false when no marker is present. Used by the
// deploy-side guard to verify the pin matches the deploy's stemcell.
func StemcellFromOps(opsYAML []byte) (sc Stemcell, ok bool) {
	sc2 := scanStemcellMarker(string(opsYAML))
	if sc2 == nil {
		return Stemcell{}, false
	}
	return *sc2, true
}

func scanStemcellMarker(s string) *Stemcell {
	scanner := bufio.NewScanner(strings.NewReader(s))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, stemcellMarkerPrefix) {
			continue
		}
		val := strings.TrimSpace(strings.TrimPrefix(line, stemcellMarkerPrefix))
		os, ver, found := strings.Cut(val, "/")
		if !found || os == "" || ver == "" {
			return nil
		}
		return &Stemcell{OS: os, Version: ver}
	}
	return nil
}
