package pve

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/ocfp/ocfp-cli-go/internal/logger"
)

// Template seeding installs the firstboot + watchdog units into a template VM
// before it is converted to a PVE template. We drive the VM via termproxy
// because PVE 9.x's snippets-upload API is blocked, the upstream Ubuntu Noble
// cloud image ships without qemu-guest-agent, and SSH to the PVE host is
// out of scope.

const (
	// templateSeedCIUser is the cloud-init user the seed step authenticates
	// as. Cloud-init creates it on first boot of the template VM. After
	// `cloud-init clean --logs` and `qm template`, cloned VMs re-run
	// cloud-init and get whatever ciuser the bloc config asks for.
	templateSeedCIUser = "ubuntu"

	// templateSeedPasswordBytes controls the entropy of the per-run
	// password generated by generateSeedPassword. 16 random bytes encoded
	// as hex yields 32 chars (128 bits of entropy).
	templateSeedPasswordBytes = 16

	// templateSeedPasswordPrefix is prepended to every generated seed
	// password so the ephemeral nature is recognisable in any logs that
	// accidentally capture it.
	templateSeedPasswordPrefix = "OcfpSeed." // #nosec G101 -- this is a label prefix prepended to a generated password, not a credential itself

	// timeouts for the seed phases. Real-world numbers from lab runs:
	// cloud-init done in ~90s, apt install in ~45s, write_files in <5s,
	// daemon-reload + enable + shutdown in <5s.
	templateSeedBootTimeout  = 240 * time.Second
	templateSeedLoginTimeout = 60 * time.Second
	templateSeedAptTimeout   = 180 * time.Second
	templateSeedShellTimeout = 30 * time.Second

	// templateSeedLoginAttempts bounds both the user names seedLogin sends
	// and the prompt waits it may retry after a timeout.
	templateSeedLoginAttempts = 4
)

// shellPromptRe matches a typical interactive prompt at end-of-buffer. We
// look for "$ " or "# " preceded by something so a single "$" in command
// output doesn't trigger early. The xterm bracketed-paste sequence (\x1b[?2004h)
// often precedes the prompt; ignore it.
var (
	loginPromptRe = regexp.MustCompile(`login:\s*$`)
	pwPromptRe    = regexp.MustCompile(`Password:\s*$`)
	shellPromptRe = regexp.MustCompile(`[\$#]\s*$`)
	anyPromptRe   = regexp.MustCompile(`(?:login:|Password:|[\$#])\s*$`)
)

// seedConsole is the part of TermproxySession that seedLogin drives, so the
// login sequence can run against a scripted console in tests.
type seedConsole interface {
	SendLine(line string) error
	ExpectRegex(re *regexp.Regexp, timeout time.Duration) (string, error)
	Drain(window time.Duration) string
}

// generateSeedPassword returns a fresh, prefixed, hex-encoded random
// password. The prefix tags the credential as ephemeral so it is
// recognisable in any incidental log capture; the random suffix supplies
// 128 bits of entropy from crypto/rand.
func generateSeedPassword() (string, error) {
	b := make([]byte, templateSeedPasswordBytes)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generate seed password: %w", err)
	}

	return templateSeedPasswordPrefix + hex.EncodeToString(b), nil
}

// seedTemplateVM connects to the template-build VM via termproxy, runs the
// seed steps the spec asks for (the firstboot + watchdog units for a bastion
// template, and an initramfs rebuild without network modules for a dracut
// image), runs cloud-init clean, and shuts the VM down so it can be
// converted to a template.
//
// The VM must already be set up with:
//   - ciuser = templateSeedCIUser
//   - cipassword = (the password argument passed here)
//   - serial0 = socket
//   - ipconfig0 = ip=dhcp, or a static ip=/gw= pair when the template
//     bridge has no DHCP (whatever lets apt reach the internet)
//   - nameserver and, optionally, searchdomain set when ipconfig0 is
//     static — cloud-init has no DHCP-supplied resolver to fall back
//     on the way DHCP mode does
//   - net0 = a bridge with internet egress
//   - agent = enabled=1 (so QEMU exposes the agent device, even though
//     the guest doesn't yet have the package installed)
//
// On return, the VM is in `stopped` state and ready for `qm template`.
func (m *ComputeManager) seedTemplateVM(ctx context.Context, node string, vmid int, password string, spec TemplateSpec) error {
	log := logger.WithOperation("seedTemplateVM")

	tokenHeader := buildPVEAPITokenHeader(m.client.config)
	if tokenHeader == "" {
		return errors.New("template seed requires API token auth (TokenID + TokenSecret)") //nolint:err113 // descriptive error, not caller-testable
	}

	log.Infof("opening termproxy to vmid %d", vmid)

	sess, err := OpenTermproxy(ctx, m.client.config.Host, tokenHeader, node, vmid, m.client.config.VerifySSL)
	if err != nil {
		return fmt.Errorf("open termproxy: %w", err)
	}

	defer func() {
		if err := sess.Close(); err != nil {
			log.Debugf("close termproxy session: %v", err)
		}
	}()

	if err := seedLogin(sess, password); err != nil {
		return fmt.Errorf("seed login: %w", err)
	}

	if err := seedPrepare(sess); err != nil {
		return fmt.Errorf("seed prepare: %w", err)
	}

	if spec.RequireBastionUnits {
		log.Infof("seeding firstboot + watchdog units")

		if err := seedWriteUnits(sess); err != nil {
			return fmt.Errorf("seed write units: %w", err)
		}
	}

	if spec.DisableInitrdNetwork {
		log.Infof("rebuilding initramfs without network modules")

		if err := seedDisableInitrdNetwork(sess); err != nil {
			return fmt.Errorf("seed disable initrd network: %w", err)
		}
	}

	if err := seedFinalize(sess); err != nil {
		return fmt.Errorf("seed finalize: %w", err)
	}

	log.Infof("seed complete; VM shutdown initiated")

	return nil
}

// seedLogin walks the login prompt → password → shell prompt sequence,
// sending wake-up CRs first because the VM may still be mid-boot when we
// connect. password is the ephemeral credential configured on the
// template VM via cloud-init.
//
// The sequence is driven by whichever prompt shows up next rather than by
// a fixed order, because on a slow first boot cloud-init keeps writing to
// ttyS0 after getty prints login:, and a prompt can be lost in that output.
// A wait that times out sends an empty line, which makes getty, login, or
// the shell print a fresh prompt, and a garbled login lands back at login:
// and starts over. Both retries are bounded by templateSeedLoginAttempts.
func seedLogin(sess seedConsole, password string) error {
	// Wake the serial; cloud-init may be writing boot messages.
	for range 3 {
		_ = sess.SendLine("")

		time.Sleep(500 * time.Millisecond)
	}

	timeout := templateSeedBootTimeout
	usersSent, nudges := 0, 0
	passwordSent := false

	for {
		out, err := sess.ExpectRegex(anyPromptRe, timeout)
		timeout = templateSeedLoginTimeout

		if err != nil {
			if !errors.Is(err, errTermproxyTimeout) || nudges >= templateSeedLoginAttempts {
				return fmt.Errorf("wait for login sequence prompt: %w", err)
			}

			nudges++

			if err := sess.SendLine(""); err != nil {
				return err
			}

			continue
		}

		switch {
		case passwordSent && shellPromptRe.MatchString(out):
			return seedShellSetup(sess)
		case usersSent > 0 && !passwordSent && pwPromptRe.MatchString(out):
			if err := sess.SendLine(password); err != nil {
				return err
			}

			passwordSent = true
		case loginPromptRe.MatchString(out):
			if usersSent >= templateSeedLoginAttempts {
				return fmt.Errorf("no shell after %d login attempts", usersSent) //nolint:err113 // descriptive error, not caller-testable
			}

			if err := sess.SendLine(templateSeedCIUser); err != nil {
				return err
			}

			usersSent++
			passwordSent = false
		default:
			// Console output that only looks like a prompt, such as a
			// boot message ending in '#'. Counted so it cannot spin.
			if nudges >= templateSeedLoginAttempts {
				return fmt.Errorf("unexpected console output before login: %q", tail(out, 200)) //nolint:err113 // descriptive error, not caller-testable
			}

			nudges++
		}
	}
}

// seedShellSetup prepares a freshly logged-in shell for marker matching.
func seedShellSetup(sess seedConsole) error {
	// Disable terminal echo so our marker matching doesn't get false
	// positives from the kernel's input echo (when we send
	// "echo OCFP_CMD_OK_X\r\n" the tty echoes those bytes back before the
	// shell runs anything; without `stty -echo` ExpectRegex would match
	// the echo and conclude the command finished prematurely, which
	// turned the whole seed flow into "send + immediately exit" with no
	// commands actually executing).
	if err := sess.SendLine("stty -echo; export PS1='PROMPT> '"); err != nil {
		return err
	}

	// Drain whatever the shell prints after PS1 changes so subsequent
	// ExpectRegex calls start from a clean buffer.
	sess.Drain(2 * time.Second)

	return nil
}

// seedPrepare waits for first-boot cloud-init to finish and quiesces the
// background apt units, so every later seed step runs against a settled
// guest. It runs for every seeded template, whatever steps follow.
func seedPrepare(sess *TermproxySession) error {
	// Wait for cloud-init to finish before we touch apt — its first-boot
	// runcmd phase holds the apt lock, and our `sudo tee` calls race with
	// it (observed empirically: file writes time out while cloud-init is
	// still emitting `Ign:` messages for apt update). The `|| true` is
	// load-bearing: cloud-init exits 2 ("recoverable error") when any
	// non-fatal module reports issues — common with apt's signature
	// warnings on first-boot — even though `status: done` is the actual
	// state we care about. We treat presence-of-boot-finished as the
	// real signal via a follow-up file check.
	if err := runShell(sess, "sudo cloud-init status --wait || true", templateSeedAptTimeout); err != nil {
		return fmt.Errorf("wait cloud-init: %w", err)
	}

	if err := runShell(sess, "test -f /var/lib/cloud/instance/boot-finished", templateSeedShellTimeout); err != nil {
		return fmt.Errorf("boot-finished sentinel missing: %w", err)
	}

	// Noble cloud images enable the apt-daily + apt-daily-upgrade +
	// unattended-upgrades timers, which fire within ~minutes of first boot.
	// They download/unpack/configure security updates — INCLUDING a newer
	// kernel — in the background. If one is mid-flight when our provisioning
	// apt runs, dpkg is left half-configured and our `apt-get install`
	// inherits the broken state (observed: `linux-image-*-generic` +
	// `initramfs-tools` post-install failing, exit 10). Quiesce the
	// background apt units, kill any in-flight run, wait for the dpkg/apt
	// locks to release, then heal any interrupted state with
	// `dpkg --configure -a` BEFORE we touch apt ourselves.
	quiesce := strings.Join([]string{
		"sudo systemctl stop apt-daily.timer apt-daily-upgrade.timer apt-daily.service apt-daily-upgrade.service unattended-upgrades.service 2>/dev/null || true",
		"sudo systemctl kill --kill-who=all apt-daily.service apt-daily-upgrade.service unattended-upgrades.service 2>/dev/null || true",
		"for _i in $(seq 1 90); do sudo fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock /var/cache/apt/archives/lock >/dev/null 2>&1 || break; sleep 2; done",
		"sudo DEBIAN_FRONTEND=noninteractive dpkg --configure -a",
	}, " && ")
	if err := runShell(sess, quiesce, templateSeedAptTimeout); err != nil {
		return fmt.Errorf("apt quiesce/heal: %w", err)
	}

	return nil
}

// seedWriteUnits installs jq + qemu-guest-agent, writes the script + unit
// files, and enables the services. seedPrepare must have run first.
func seedWriteUnits(sess *TermproxySession) error {
	// Refresh package metadata first: cloud-init's default
	// `package_update_upgrade_install` only fetches if upgrades are
	// requested, leaving the apt cache empty on noble cloud images.
	// Without this, `apt install` reports "Unable to locate package".
	if err := runShell(sess, "sudo DEBIAN_FRONTEND=noninteractive apt-get update -q", templateSeedAptTimeout); err != nil {
		return fmt.Errorf("apt update: %w", err)
	}

	// apt non-interactive; jq required by firstboot/watchdog scripts; agent
	// useful for future operator introspection (qm guest exec works after
	// this is installed).
	aptCmd := "sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -q --no-install-recommends jq qemu-guest-agent"
	if err := runShell(sess, aptCmd, templateSeedAptTimeout); err != nil {
		return fmt.Errorf("apt install: %w", err)
	}

	for _, f := range seedUnitFiles() {
		if err := writeRemoteFile(sess, f.path, f.content, f.mode); err != nil {
			return fmt.Errorf("write %s: %w", f.path, err)
		}
	}

	for _, c := range seedEnableCommands() {
		if err := runShell(sess, c, templateSeedShellTimeout); err != nil {
			return fmt.Errorf("%s: %w", c, err)
		}
	}

	return nil
}

// seedDisableInitrdNetwork writes the dracut drop-in that leaves the network
// modules out of the initramfs, rebuilds every installed kernel's initramfs,
// and then checks each one, so a template is never converted while an
// initramfs could still bring the NIC up. The drop-in stays in the image,
// so initramfs rebuilds after a kernel update in a clone honour it too.
func seedDisableInitrdNetwork(sess *TermproxySession) error {
	if err := writeRemoteFile(sess, initrdNoNetworkConfPath, initrdNoNetworkConf, "0644"); err != nil {
		return fmt.Errorf("write %s: %w", initrdNoNetworkConfPath, err)
	}

	if err := writeRemoteFile(sess, initrdNoNetworkScriptPath, initrdNoNetworkScript, "0755"); err != nil {
		return fmt.Errorf("write %s: %w", initrdNoNetworkScriptPath, err)
	}

	// Rebuilding takes about 15 seconds per kernel, and a fresh cloud
	// image carries one or two kernels.
	run := fmt.Sprintf("sudo bash %s && sudo rm -f %s", initrdNoNetworkScriptPath, initrdNoNetworkScriptPath)
	if err := runShell(sess, run, templateSeedAptTimeout); err != nil {
		return fmt.Errorf("rebuild initramfs: %w", err)
	}

	return nil
}

// seedFinalize runs cloud-init clean (so cloned VMs re-run cloud-init with
// their own per-VM config) and shuts the VM down. We do NOT wait for the
// shell prompt after shutdown because the session dies as soon as systemd
// stops the getty.
func seedFinalize(sess *TermproxySession) error {
	if err := runShell(sess, "sudo cloud-init clean --logs", templateSeedShellTimeout); err != nil {
		return fmt.Errorf("cloud-init clean: %w", err)
	}

	// Fire-and-forget shutdown. ExpectRegex will see connection close and
	// return; ignoring its result is fine.
	_ = sess.SendLine("sudo shutdown -h now")

	time.Sleep(2 * time.Second)

	return nil
}

// runShell sends a command and waits for an exit-code-tagged sentinel that
// proves the command ran (regardless of exit status). The sentinel includes
// $? so we can distinguish "command finished with non-zero exit" from
// "command never ran" and surface real failures.
func runShell(sess *TermproxySession, cmd string, timeout time.Duration) error {
	tag := fmt.Sprintf("OCFP_CMD_DONE_%d", time.Now().UnixNano())
	// Use `;` so the marker prints even when the command fails. Capture
	// $? in the marker so non-zero exit codes are observable.
	wrapped := fmt.Sprintf("%s ; printf '\\n%s:%%d\\n' $?", cmd, tag)

	if err := sess.SendLine(wrapped); err != nil {
		return err
	}

	// Match the marker AND the exit code that follows it.
	markerSpecific := regexp.MustCompile(regexp.QuoteMeta(tag) + `:(\d+)`)

	out, err := sess.ExpectRegex(markerSpecific, timeout)
	if err != nil {
		return fmt.Errorf("%w (output tail: %q)", err, tail(out, 400))
	}

	if matches := markerSpecific.FindStringSubmatch(out); len(matches) == 2 && matches[1] != "0" {
		return fmt.Errorf("command exited %s (output tail: %q)", matches[1], tail(out, 400)) //nolint:err113 // descriptive error, not caller-testable
	}

	return nil
}

// writeRemoteFile base64-encodes the content locally and writes it on the
// remote via `tee` + `chmod`. base64 avoids shell-quoting headaches for
// arbitrary script content.
func writeRemoteFile(sess *TermproxySession, path, content, mode string) error {
	b64 := base64.StdEncoding.EncodeToString([]byte(content))

	// We talk to the VM over a serial console, whose tty runs in canonical
	// mode. The Linux line discipline caps a single input line at MAX_CANON
	// (4096 bytes); a longer line blocks at the line discipline, never reaches
	// the shell, and eventually tears down the termproxy websocket
	// ("close 1006: unexpected EOF"). The firstboot + watchdog scripts
	// base64-encode to ~5KB, so a one-shot `echo '<b64>'` deterministically
	// exceeds the limit. Stream the encoded payload to a temp file in short
	// chunks (one well-under-MAX_CANON line each), then decode it remotely.
	const (
		seedTmp   = "/tmp/ocfp-seed.b64"
		chunkSize = 512
	)

	// Truncate the temp file (writable by the cloud-init user; no sudo needed
	// in /tmp).
	if err := runShell(sess, ": > "+seedTmp, templateSeedShellTimeout); err != nil {
		return fmt.Errorf("init temp for %s: %w", path, err)
	}

	for start := 0; start < len(b64); start += chunkSize {
		end := min(start+chunkSize, len(b64))

		// printf '%s' keeps the chunk on one short line with no payload
		// newline; the base64 alphabet excludes the single quote, so
		// single-quoting is safe.
		cmd := fmt.Sprintf("printf '%%s' '%s' >> %s", b64[start:end], seedTmp)
		if err := runShell(sess, cmd, templateSeedShellTimeout); err != nil {
			return fmt.Errorf("append chunk to %s: %w", path, err)
		}
	}

	final := fmt.Sprintf("base64 -d %s | sudo tee %s >/dev/null && sudo chmod %s %s && rm -f %s",
		seedTmp, path, mode, path, seedTmp)
	if err := runShell(sess, final, templateSeedShellTimeout); err != nil {
		return fmt.Errorf("decode/write %s: %w", path, err)
	}

	return nil
}

// buildPVEAPITokenHeader assembles the "PVEAPIToken=<id>=<secret>" header
// value termproxy needs. Returns "" if either field is unset.
func buildPVEAPITokenHeader(cfg *Config) string {
	if cfg.TokenID == "" || cfg.TokenSecret == "" {
		return ""
	}

	return "PVEAPIToken=" + strings.TrimSpace(cfg.TokenID) + "=" + strings.TrimSpace(cfg.TokenSecret)
}
